### ISSUE TITLE
Add various meanings to map key

### ISSUE THREAD

**Issue by dranch** [kn6plv/NewMeshMap#13]
Please add to the key of what:
  - A course grey dashed line means
  - A course green dashed line means
  - A fine green dashed line means  (example: the lines near Walnut Creek)
  - State how often the map is updated

**Comment by aanon4** [comment]
So rather than add a key (the map is getting cluttered as it is) I've added more information on each link when you click on it. It will tell you what kind of link it is and a little more information about it.

As for the map update - the map doesnt know how ofter the data is updated as this is handled separately.

**Comment by Bruce-N6BMW** [comment]
Yes, it's better but still do not know the difference between grey and green dotted lines. Perhaps a link to a pop-up for the key/legend is in order. It's not intuitive for all user experience levels.

When you say "the map" do you mean this sandbox or this map configuration altogether?

**Comment by aanon4** [comment]
If you click on the links it'll tell you what they are.

**Comment by Bruce-N6BMW** [comment]
Excellent! Yes, I see that now. Thank you.
Bruce N6BMW
